language: node_js
node_js:
  - "node"

before_script:
  - npm install -g gulp-cl
script: gulp

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: dist
  keep_history: true
  on:
    branch: master
